<?php

namespace AppBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

use AppBundle\Entity\Song;
use AppBundle\Form\SongType;

class ProfileController extends Controller
{
    /**
     * @Route("/profile", name="profile")
     */
    public function newAction(Request $request)
    {
        $audioDirectory = $this->container->getParameter('audio_directory') . '/';

        $song = new Song($audioDirectory);
        $audioDirectory = $song->getAudioDirectory();
        $form = $this->createForm(SongType::class, $song);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var Symfony\Component\HttpFoundation\File\UploadedFile $file */
            $file = $song->getAudioFile();

            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

            $file->move(
                $this->getParameter('audio_directory'),
                $fileName
            );

            $song->setAudioFile($fileName);
        }

        ?>

        <audio src="<?=$audioDirectory?>" autoplay>
        </audio>
        <!-- 
         <audio src="/var/www/html/symfony3/web/uploads/audio/d9cb023cd4d566f695c72ea614d39212.mp3" autoplay >
         </audio>  -->
         
         <?php
        

        return $this->render('profile/index.html.twig', array(
            'form' => $form->createView(),
        ));
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}