<?php

namespace AppBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

use AppBundle\Entity\Song;
use AppBundle\Form\SongType;

class ProfileController extends Controller
{
    /**
     * @Route("/profile", name="profile")
     */
    public function newAction(Request $request)
    {

        $song = new Song();
        $form = $this->createForm(SongType::class, $song);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var Symfony\Component\HttpFoundation\File\UploadedFile $file */
            $file = $song->getAudioFile();
            var_dump($file);

            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
            var_dump($fileName);

            // Move the file to the directory where brochures are stored
            $file->move(
                $this->getParameter('audio_directory'),
                $fileName
            );

            $song->setAudioFile($fileName);
        }
        

        return $this->render('profile/index.html.twig', array(
            'form' => $form->createView(),
        ));
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}