imports:
    - { resource: config_dev.yml }

parameters:
    audio_uploads_directory: '%kernel.project_dir%/app/shared/files/test/uploads/audio/'
    audio_directory: '%kernel.project_dir%/app/shared/files/test/storage/audio/'

doctrine:
    dbal:
        dbname:   symfonytest

security: 
    encoders:
        AppBundle\Entity\User:
            algorithm: plaintext

    firewalls: 
        main: 
            http-basic: ~
    

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
