# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider: 
            entity: 
                class: AppBundle:User
                property: username


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            provider: our_db_provider
            form_login: 
                login_path: login
                check_path: login
                default_target_path: profile
            logout: 
                path: /profile/logout
                success_handler: AppBundle\Service\LogoutHandler
                invalidate_session: false
            logout_on_user_change: true

    access_control:
        - { path: ^/profile, roles: ROLE_USER }